import {
  LayoutDashboard,
  TestTube,
  Package,
  Calendar,
  CreditCard,
  Building2,
  FileText,
  Tag,
  Users,
  Settings,
  ClipboardList,
  Upload,
  UserCog,
  Landmark,
} from 'lucide-react'

export const sidebarMenuByRole = {
  admin: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/admin' },
    { label: 'Tests', icon: TestTube, route: '/admin/tests', permission: { resource: 'tests', action: 'read' } },
    { label: 'Packages', icon: Package, route: '/admin/packages', permission: { resource: 'packages', action: 'read' } },
    { label: 'Bookings', icon: Calendar, route: '/admin/bookings', permission: { resource: 'bookings', action: 'read' } },
    { label: 'Payments', icon: CreditCard, route: '/admin/payments', permission: { resource: 'payments', action: 'read' } },
    { label: 'Settlements', icon: Landmark, route: '/admin/settlements', permission: { resource: 'settlements', action: 'read' } },
    { label: 'Lab Owners', icon: Building2, route: '/admin/lab-owners', permission: { resource: 'lab_owners', action: 'read' } },
    { label: 'Reports', icon: FileText, route: '/admin/reports', permission: { resource: 'reports', action: 'read' } },
    { label: 'Offers', icon: Tag, route: '/admin/offers', permission: { resource: 'offers', action: 'read' } },
    { label: 'Users', icon: Users, route: '/admin/users', permission: { resource: 'users', action: 'read' } },
    { label: 'Settings', icon: Settings, route: '/admin/settings', permission: { resource: 'roles', action: 'read' } },
  ],
  lab_owner: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/lab-owner' },
    { label: 'Assistants', icon: Users, route: '/lab-owner/assistants', permission: { resource: 'lab_assistants', action: 'read' } },
    { label: 'Tests', icon: TestTube, route: '/lab-owner/tests', permission: { resource: 'tests', action: 'read' } },
    { label: 'Packages', icon: Package, route: '/lab-owner/packages', permission: { resource: 'packages', action: 'read' } },
    { label: 'Bookings', icon: Calendar, route: '/lab-owner/bookings', permission: { resource: 'bookings', action: 'read' } },
    { label: 'Sample Pickups', icon: ClipboardList, route: '/lab-owner/sample-pickups', permission: { resource: 'bookings', action: 'read' } },
    { label: 'Upload Reports', icon: Upload, route: '/lab-owner/upload-reports', permission: { resource: 'bookings', action: 'update' } },
    { label: 'Lab Profile', icon: UserCog, route: '/lab-owner/lab-profile', permission: { resource: 'lab_owners', action: 'read' } },
    { label: 'Payments', icon: CreditCard, route: '/lab-owner/payments', permission: { resource: 'payments', action: 'read' } },
    { label: 'Settlements', icon: Landmark, route: '/lab-owner/settlements', permission: { resource: 'settlements', action: 'read' } },
    { label: 'Reports', icon: FileText, route: '/lab-owner/reports', permission: { resource: 'reports', action: 'read' } },
  ],
  lab_assistant: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/lab-assistant' },
    { label: 'Tests', icon: TestTube, route: '/lab-assistant/tests', permission: { resource: 'tests', action: 'read' } },
    { label: 'Packages', icon: Package, route: '/lab-assistant/packages', permission: { resource: 'packages', action: 'read' } },
    { label: 'Sample Pickups', icon: ClipboardList, route: '/lab-assistant/sample-pickups', permission: { resource: 'bookings', action: 'read' } },
    { label: 'Upload Reports', icon: Upload, route: '/lab-assistant/upload-reports', permission: { resource: 'bookings', action: 'update' } },
    { label: 'Bookings', icon: Calendar, route: '/lab-assistant/bookings', permission: { resource: 'bookings', action: 'read' } },
  ],
  patient: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/dashboard' },
    { label: 'Tests', icon: TestTube, route: '/booking/tests', permission: { resource: 'tests', action: 'read' } },
    { label: 'Packages', icon: Package, route: '/booking/packages', permission: { resource: 'packages', action: 'read' } },
    { label: 'My Bookings', icon: Calendar, route: '/booking/bookings', permission: { resource: 'bookings', action: 'read' } },
    { label: 'Upload Prescription', icon: Upload, route: '/upload-prescription', permission: { resource: 'bookings', action: 'create' } },
    { label: 'Reports', icon: FileText, route: '/booking/reports', permission: { resource: 'reports', action: 'read' } },
  ],
}
