import {
  LayoutDashboard,
  TestTube,
  Package,
  Calendar,
  CreditCard,
  Building2,
  FileText,
  Tag,
  Users,
  Settings,
  ClipboardList,
  Upload,
  UserCog,
} from 'lucide-react'

export const sidebarMenuByRole = {
  admin: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/admin' },
    { label: 'Tests', icon: TestTube, route: '/admin/tests' },
    { label: 'Packages', icon: Package, route: '/admin/packages' },
    { label: 'Bookings', icon: Calendar, route: '/admin/bookings' },
    { label: 'Payments', icon: CreditCard, route: '/admin/payments' },
    { label: 'Lab Owners', icon: Building2, route: '/admin/lab-owners' },
    { label: 'Reports', icon: FileText, route: '/admin/reports' },
    { label: 'Offers', icon: Tag, route: '/admin/offers' },
    { label: 'Users', icon: Users, route: '/admin/users' },
    {
      label: 'Settings',
      icon: Settings,
      route: '/admin/settings',
      children: [
        { label: 'General Settings', route: '/admin/settings/general' },
        { label: 'Categories', route: '/admin/settings/categories' },
        { label: 'Subcategories', route: '/admin/settings/subcategories' },
        { label: 'Test Parameters', route: '/admin/settings/parameters' },
        { label: 'Sample Types', route: '/admin/settings/sample-types' },
        { label: 'Report Time (TAT)', route: '/admin/settings/tat' },
        { label: 'Email Templates', route: '/admin/settings/email-templates' },
      ],
    },
  ],
  lab_owner: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/lab-owner' },
    { label: 'Tests', icon: TestTube, route: '/lab-owner/tests' },
    { label: 'Bookings', icon: Calendar, route: '/lab-owner/bookings' },
    { label: 'Sample Pickups', icon: ClipboardList, route: '/lab-owner/sample-pickups' },
    { label: 'Upload Reports', icon: Upload, route: '/lab-owner/upload-reports' },
    { label: 'Lab Profile', icon: UserCog, route: '/lab-owner/lab-profile' },
    { label: 'Payments', icon: CreditCard, route: '/lab-owner/payments' },
    { label: 'Reports', icon: FileText, route: '/lab-owner/reports' },
  ],
  lab_assistant: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/lab-assistant' },
    { label: 'Sample Pickups', icon: ClipboardList, route: '/lab-assistant/sample-pickups' },
    { label: 'Upload Reports', icon: Upload, route: '/lab-assistant/upload-reports' },
    { label: 'Bookings', icon: Calendar, route: '/lab-assistant/bookings' },
  ],
  patient: [
    { label: 'Dashboard', icon: LayoutDashboard, route: '/booking' },
    { label: 'My Bookings', icon: Calendar, route: '/booking/history' },
    { label: 'Upload Prescription', icon: Upload, route: '/upload-prescription' },
    { label: 'Reports', icon: FileText, route: '/patient/reports' },
  ],
}
